target 'Chuchi' do
pod 'Firebase'
pod 'FirebaseDatabase'
pod 'INTULocationManager'
pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'
pod 'AFNetworking', '~> 2.5'
pod 'MBProgressHUD'
end

target 'ChuchiSiriExtension' do
end